#!/bin/bash

# hanguru.school 서버 배포 스크립트
# 사용법: ./deploy-commands.sh

echo "🚀 hanguru.school Next.js 앱 배포 시작"
echo "=================================="

# 1. 파일 업로드
echo "📤 1단계: 파일 업로드"
echo "다음 명령어를 실행하세요:"
echo "scp hanguru-app-deploy.tar.gz user@hanguru.school:/tmp/"
echo ""

# 2. 서버 접속 및 설정
echo "🔧 2단계: 서버 설정"
echo "다음 명령어들을 순서대로 실행하세요:"
echo ""
echo "# 서버 접속"
echo "ssh user@hanguru.school"
echo ""
echo "# 디렉터리 생성 및 파일 이동"
echo "sudo mkdir -p /var/www/hanguru-app"
echo "sudo chown \$USER:\$USER /var/www/hanguru-app"
echo "cd /var/www/hanguru-app"
echo "tar -xzf /tmp/hanguru-app-deploy.tar.gz"
echo ""
echo "# 의존성 설치"
echo "npm install --production"
echo ""
echo "# PM2 설치 및 실행"
echo "npm install -g pm2"
echo "pm2 start npm --name 'hanguru-app' -- start"
echo "pm2 startup"
echo "pm2 save"
echo ""

# 3. nginx 설정
echo "🌐 3단계: nginx 설정"
echo "nginx 설정 파일에 다음 내용을 추가하세요:"
echo ""
echo "sudo nano /etc/nginx/sites-available/hanguru.school"
echo ""
echo "다음 내용을 location / 블록 다음에 추가:"
echo "=================================="
echo "    # Next.js 앱 (서브 디렉터리)"
echo "    location /app/ {"
echo "        # 브라우저만 허용"
echo "        if (\$http_user_agent !~* \"(Mozilla|Chrome|Safari|Edge|Opera|Firefox)\") {"
echo "            return 403;"
echo "        }"
echo "        "
echo "        # Next.js로 프록시"
echo "        proxy_pass http://localhost:3000;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "        "
echo "        # 보안 헤더"
echo "        proxy_hide_header X-Powered-By;"
echo "        add_header X-Frame-Options \"DENY\" always;"
echo "        add_header X-Content-Type-Options \"nosniff\" always;"
echo "    }"
echo "=================================="
echo ""

# 4. nginx 재시작
echo "🔄 4단계: nginx 재시작"
echo "sudo nginx -t"
echo "sudo systemctl reload nginx"
echo ""

# 5. 테스트
echo "🧪 5단계: 배포 테스트"
echo "다음 URL로 접속 테스트:"
echo "https://hanguru.school/app/"
echo ""
echo "브라우저에서 정상 접속되는지 확인하세요!"
echo ""

echo "✅ 배포 완료!"
echo "=================================="
echo "접속 URL:"
echo "- 워드프레스: https://hanguru.school/"
echo "- Next.js 앱: https://hanguru.school/app/"
echo "- IC 카드 등록: https://hanguru.school/app/tagging/home"
echo "- 관리자: https://hanguru.school/app/admin/"
echo "==================================" 