name: Auto Deploy to Production

on:
  push:
    branches: [feature/production-system-setup]
  workflow_dispatch:

jobs:
  auto-merge-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      statuses: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Merge to main
        run: |
          git checkout main
          git pull origin main
          git merge origin/feature/production-system-setup --no-edit
          git push origin main

      - name: Wait for deployment
        run: |
          echo "Waiting for Vercel deployment to start..."
          sleep 30

      - name: Check deployment status
        run: |
          echo "Deployment initiated successfully!"
          echo "Check Vercel dashboard for deployment status" 